name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore ./DynamicExpressionBuilder/DynamicExpressionBuilder.csproj
    - name: Build Project
      run: dotnet build ./DynamicExpressionBuilder/DynamicExpressionBuilder.csproj --configuration release
    - name: Pack project
      run: dotnet pack ./DynamicExpressionBuilder/DynamicExpressionBuilder.csproj --output nuget-packages --configuration Release
    - name: Push to Nuget
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
